config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # crud

  # root
  root to: 'articles#index'

  # 23:45 note: had to be moved up because of the issue with :id as string, needs to be above show
  # C
  # new
  get 'articles/new', to: 'articles#new' #articles_new
  # create
  # unsure where to send post after new
  # this is correct
  post 'articles', to: 'articles#create'

  # R
  # index
  get 'articles', to: 'articles#index'
  # show
  get 'articles/:id', to: 'articles#show', as: :article



  # U
  # edit
  get 'articles/:id/edit', to: 'articles#edit', as: :edit_article
  # update
  # unsure where to send this too... feels like you see the article/id
  patch 'articles/:id', to: 'articles#update'

  # D
  # destroy
  delete 'articles/:id', to: 'articles#destroy', as: :destroy_article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # R
  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def show
  end


  # C
  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)

    redirect_to articles_path
  end


  # U
  def edit

  end

  def update
    @article.update(article_params)

    redirect_to article_path(@article)
  end


  # D
  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-info' %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit this article:</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class="my-3 border-bottom">
    <h4><%= link_to article.title, article_path(article), class: 'text-info' %></h4>
    <p><%= article.content[0..90].gsub(/\s\w+$/,'...') %></p>
  </div>
<% end %>

app/views/articles/new.html.erb
<h1>Compose your article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="pb-3 mb-4 border-bottom">
  <%= link_to 'Edit this article', edit_article_path(@article), class: 'btn btn-info' %>
  <%= link_to 'Delete this article', destroy_article_path(@article), method: :delete, class: 'btn btn-danger ml-2' %>
</div>

<h1 class="mb-4"><%= @article.title %></h1>
<p><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light mb-4">
      <a class="navbar-brand text-info" href="/">Wikinimous</a>

      <%= link_to '+ New article', articles_new_path, class: 'btn btn-warning' %>
    </nav>
    <div class="container">
      <div class="col-12 offset-lg-2 col-lg-8">
        <%= yield %>
      </div>
    </div>
  </body>
</html>